"""
convert_to_fm24.py
Converts an XML generated by split_fm_xml.py (FM 2021 format)
into the format accepted by the FM 2024 editor.

Includes automatic remapping of the 28 player_ids created in FM 2021
that FM 2024 does not recognise (range 2,000,066,xxx).
Formula: player_id_new = player_id_retro - 60238
Confirmed in testing with italy_fm24_final.xml (all 28 players imported successfully).

Usage:
    python convert_to_fm24.py italy
    python convert_to_fm24.py spain
    Input:  output/fm21/<name>.xml
    Output: output/fm24/<name>_fm24_final.xml
"""

import sys
import os

# ── configuration ────────────────────────────────────────────────────────────

TARGET = sys.argv[1] if len(sys.argv) > 1 else "italy"

BASE_DIR    = os.path.dirname(os.path.abspath(__file__))
INPUT_PATH  = os.path.join(BASE_DIR, "output", "fm21", f"{TARGET}.xml")
OUTPUT_PATH = os.path.join(BASE_DIR, "output", "fm24", f"{TARGET}_fm24_final.xml")

os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)

FM24_HEADER = (
    "<record>\n"
    "\t<list id=\"verf\">\n"
    "\t\t<string value=\"24.0.0\"/>\n"
    "\t</list>\n"
    "\t<integer id=\"XSvC\" value=\"209\"/>\n"
    "\t<string id=\"EdBr\" value=\"main\"/>\n"
    "\t<date id=\"EdDt\" day=\"16\" month=\"5\" year=\"2025\" time=\"0000\"/>\n"
    "\t<integer id=\"version\" value=\"3569\"/>\n"
    "\t<integer id=\"rule_group_version\" value=\"1536\"/>\n"
    "\t<boolean id=\"beta\" value=\"false\"/>\n"
    "\t<string id=\"orvs\" value=\"\"/>\n"
    "\t<string id=\"svvs\" value=\"2400\"/>\n"
    "\t<string id=\"description\" value=\"\"/>\n"
    "\t<string id=\"author\" value=\"\"/>\n"
    "\t<integer id=\"EDvb\" value=\"1\"/>\n"
    "\t<string id=\"EDfb\" value=\"\"/>\n"
    "\t<list id=\"db_changes\">\n"
)

FM24_FOOTER = "\t</list>\n</record>\n"

# ── record version mapping FM 2021 → FM 2024 ─────────────────────────────────
VERSION_MAP = {
    'id="version" value="2959"': 'id="version" value="3567"',
    'id="version" value="2961"': 'id="version" value="3567"',
}

IS_CLIENT  = '<boolean id="is_client_field" value="true"/>'
ODVL_FALSE = '<boolean id="odvl" value="false"/>'

# ── problematic ID remapping ──────────────────────────────────────────────────
# player_ids in the range 2,000,040,000–2,000,070,000 existed in FM 2021 but not
# in the FM 2024 base database, which silently ignores them.
# Offset -60238 brings them into the 1,999,980,xxx–2,000,010,xxx range, accepted by FM 2024.
# Derived from the Totti case (2000066931 → 2000006693) and confirmed across 46 players
# (28 Italian + 18 Spanish).
MULT             = 2**32 + 1
OFFSET           = 60238
PROBLEMATIC_LOW  = 2_000_040_000
PROBLEMATIC_HIGH = 2_000_070_000

def _build_remap(xml_path):
    """Read the XML and build the substitution dict for IDs in the problematic range."""
    import re
    remap = {}
    seen = set()
    with open(xml_path, encoding="utf-8") as f:
        for line in f:
            m = re.search(r'db_unique_id" value="(\d+)"', line)
            if not m:
                continue
            uid = int(m.group(1))
            if uid in seen:
                continue
            seen.add(uid)
            q, r = divmod(uid, MULT)
            if r == 0 and PROBLEMATIC_LOW <= q <= PROBLEMATIC_HIGH:
                remap[str(uid)] = str((q - OFFSET) * MULT)
    return remap

ID_REMAP = _build_remap(INPUT_PATH)

# ── streaming conversion ──────────────────────────────────────────────────────

records_written = 0
in_db_changes   = False

with open(INPUT_PATH, "r", encoding="utf-8") as fin, \
     open(OUTPUT_PATH, "w", encoding="utf-8") as fout:

    fout.write(FM24_HEADER)

    for line in fin:
        if not in_db_changes:
            if '<list id="db_changes">' in line:
                in_db_changes = True
            continue

        if line.rstrip("\n") in ("\t</list>", "</record>"):
            break

        # remap problematic IDs
        for old_uid, new_uid in ID_REMAP.items():
            if old_uid in line:
                line = line.replace(old_uid, new_uid)
                break

        # FM 2021 → FM 2024 version numbers
        for old, new in VERSION_MAP.items():
            if old in line:
                line = line.replace(old, new)
                break

        # is_client_field → odvl
        if IS_CLIENT in line:
            line = line.replace(IS_CLIENT, ODVL_FALSE)

        fout.write(line)

        if line.strip() == "<record>":
            records_written += 1

    fout.write(FM24_FOOTER)

print(f"Input  : {INPUT_PATH}")
print(f"Output : {OUTPUT_PATH}")
print(f"Records: {records_written}")
